package day07;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day07Test {

    private static final String INPUT = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";

    @Test
    void testProcessPart1() {
        var result = Day07.processPart1(INPUT);
        assertEquals(Integer.valueOf(21), result);
    }

    @Test
    void testProcessPart2() {
        var result = Day07.processPart2(INPUT);
        assertEquals(Integer.valueOf(40), result);
    }
}

